apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helm_service_3e8360d64d54565fa79cffc070406be1.name   }}
spec:
  type: {{ .Values.helm_service_3e8360d64d54565fa79cffc070406be1.type }}
  ports:
    - port: {{ .Values.helm_service_3e8360d64d54565fa79cffc070406be1.port }}
      targetPort: {{ .Values.helm_service_3e8360d64d54565fa79cffc070406be1.target_port }}
      protocol: {{.Values.helm_service_3e8360d64d54565fa79cffc070406be1.protocol}}
  {{- with .Values.helm_service_3e8360d64d54565fa79cffc070406be1.selector_labels }}
  selector:
      {{- toYaml . | nindent 8 }}
  {{- end }}